### ISSUE TITLE
Old versions of OpenSSL are gonna be difficult to find

### ISSUE THREAD

**Issue by Darthagnon** [sepalani/MH3SP#11]
I was looking through https://github.com/sepalani/MH3SP/wiki/Configuration/_compare/a165dab%5E...a165dab
and had a thought; older OpenSSL versions are going to be difficult to find, as [devs like this one](https://slproweb.com/products/Win32OpenSSL.html) don't supply older versions. I tried looking around, but couldn't find any reliable sources or `golden version` supporting SHA-1 (according to [Wikipedia](https://en.wikipedia.org/wiki/OpenSSL), the current version still supports SHA-1?)

**Comment by Darthagnon** [comment]
[The cited website](https://serverfault.com/questions/744076) suggests `v1.0.1` is the `golden version` for MH3SP

**Comment by sepalani** [comment]
That's a shame, there were removed lately:
 - https://indy.fulgan.com/SSL/Archive/
![image](https://user-images.githubusercontent.com/7890055/135972097-835ebea4-b843-472a-bc24-b37662a53c27.png)

I'll try to find another place where you can download them.
