### ISSUE TITLE
Cant acces after 7 h

### ISSUE THREAD

**Issue by mhtrifan** [sepalani/MH3SP#119]
Before 7 hours , so 18:00 in Germany , everything was fine and I could play online but now i cant join the servers. I think they are offline now becouse I tried to go into online without the mh3sp version and it just loaded up to 20% but at the project verson loc lac loaded up to 75%. Can you pls tell me if Im right? My current time is 2:00.

**Comment by sepalani** [comment]
This doesn't seem related to the server code but the beta access. Feel free to seek for help on Discord.
