### ISSUE TITLE
Quest Box Capitalization Errors

### ISSUE THREAD

**Issue by realSquidCoder** [sepalani/MH3SP#125]
"deliver" is not capitalized when depositing items for a quest.
![Screenshot_20240105_194214_Dolphin Emulator](https://github.com/sepalani/MH3SP/assets/92821989/ac69ab97-5de8-4c2c-bf4c-998d921fabc5)
![Screenshot_20240105_192235_Dolphin Emulator](https://github.com/sepalani/MH3SP/assets/92821989/3f1962be-1d79-4e4a-b0db-82ecb23f9327)

**Comment by sepalani** [comment]
Unless I'm mistaken, this typo is from the game not the server. If you believe that's not the case, feel free to provide a footage of the game before the shutdown showing where this typo isn't present and reopen the issue.
