### ISSUE TITLE
[Typo] "Veggie Elder, the"

### ISSUE THREAD

**Issue by realSquidCoder** [sepalani/MH3SP#126]
![Screenshot_20240106_204159_Dolphin Emulator](https://github.com/sepalani/MH3SP/assets/92821989/a9b2698f-12e4-49cb-b1f8-a96b4922dc12)
Unable to check if the original had it like this, but I find it really hard to believe it was. Sorry if this should have been reported.

**Comment by sepalani** [comment]
@realSquidCoder 
As mentioned in https://github.com/sepalani/MH3SP/issues/125, this doesn't seem related to the server but are mistakes made by Capcom.
