### ISSUE TITLE
Command Panel

### ISSUE THREAD

**Issue by Asso0123** [sepalani/MH3SP#17]
Hi, I'm Alessandro, I'm from Italy, i was trying to patch the certificate for my region in the command panel, but the panel, after i put:

C:\Python27\Python.exe MHTriCertPatcher.py -P main.dol ca.der ;

It says that: DOL doesn't seem to be from the DATA partition! 

I really don't know how to go on with the procedure, please help! 
Sorry for the disturb, have a nice day!

**Comment by sepalani** [comment]
Your `main.dol` is probably from the game's UPDATE partition rather than the game's DATA partition. Feel free to join the Discord server to seek for assistance.
