### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by DefeatedGamer** [sepalani/MH3SP#2]
@sepalani 
Is this still being worked on, or is it just a dead project? I have followed another MH3 server project, but the creator gave up. I was wondering if I could help in any way. 

**_Email-_** armoredbattlewalrus@gmail.com

**Comment by DefeatedGamer** [comment]
I know for a fact your largest problem was (and probably still is) the figurative 'handshake' between the console and server. The data fetch can't find anything because there is nothing. Last I checked not one person has cloned the server code, so the only thing that can happen is spending endless hours piecing together exactly what it's looking for based on what the code is lacking. I was taught when doing this, run a tracking program to locate individual requests, it runs the code step-by-step until there is missing information (similar to debugging) then shows all relevant information. This can only be helpful if the code is specific enough and doesn't use titles given by coders, but can reveal what it wants, such as an entity or function. And  please learn from all the other server projects mistakes, gather the MH3U data while you still can! This project may just be too far gone, but MH3U will inevitably be shut down and I'm sure people would be more than willing to use an emulator; if the necessary info can be retrieved and the server communication process is saved then there will be hope for MH3U.

**Comment by sepalani** [comment]
To answer your question, you can consider this project as "dead". To be honest, I don't spend all my free-time into this project, plus I have less and less time to do so. However, if someone one want to fork this project, that person can with github and improve it.

Concerning my issue, unless there is another underlying communication in the SSL communication, I don't have any issue with the "handshake", I just need to know what to send to the game. I use my custom certificate with a custom Dolphin Emulator and my altwfc fork.

Finally I don't plan to dump MH3U which is less interesting IMO than MH3. Those games are on WiiU and 3DS, I leave that task to the WiiU/3DS community, I don't have enough experience for that. By the way, my WiiU/3DS aren't softmodded and current emulators aren't features rich and stable enough to help me in that task.

**Comment by DefeatedGamer** [comment]
Thank you for your kind worded response, I have had trouble dealing with
some people. And I personally also believe that monster hunter lost quality
after the console upgrade, it got too complicated and had too many factors
to consider during gameplay. I wish you a good day, good luck with anything
else you are working on. I plan to fork your project and possibly take it
to the next step, the check list you provided was very appreciated.

**Comment by Radu13** [comment]
Hello @sepalani @DefeatedGamer i am also interested in this project and unlike other mh, the private server is the only way to enter again to LOC-LAC.
@sepalani did you thinked about making a team for improving this project and maybe finally complete it?

**Comment by sepalani** [comment]
Hello @Radu13. My situation hasn't changed since last time, so that's quite unlikely. Feel free to make a team and continue the project if you have the time to.

**Comment by Radu13** [comment]
All right @sepalani I'll try that!
Thanks anyway!
You can suggest me a good way for reverse the mh3 remaining code?

**Comment by GrandGizzard** [comment]
Is anyone still working on this project? I’ve looked all over the net for updates about this, and it seems all the commotion is dead now. It makes me sad, I miss Loc Lac..

**Comment by Radu13** [comment]
@GrandGizzard hello, me and Oversoul will create a discord server dedicated to this project soon, eventually @sepalani and ngevan2k  join us as well.
If we talk about this project on mh and hack forums, lots of talented people gonna join us well and maybe we can finish this project! :D

**Comment by GrandGizzard** [comment]
Is ngevan2k still active? What has he been up to these days? Haven’t heard from him in years..

**Comment by Radu13** [comment]
He posted something on gamefaqs this year, also his forums still are online as well

**Comment by ShinoBin** [comment]
@Radu13 Let me know when you have that server up. My reversing skills aren't up to snuff yet but I'll still see if there's anything I can do to help out, even if it's just cheering from the sidelines.

**Comment by danielloera** [comment]
Hello! Also interested in helping out.

**Comment by Dixdros** [comment]
hello is the project dead?

**Comment by NightDragon98** [comment]
Hello, the group of people who made the private servers for Monster Hunter 1 and Monster Hunter G, Dixdros, the person who commented before is a part of, are wondering if you have the packet captures for MH Tri's servers still? or is everything you have uploaded on GitHub all you have for the project?

**Comment by Superdoom4u** [comment]
hey i have a question forgive me for not knowing but i looked monster hunter tri up on wiimmfi and it said that online/wiimmfi was disabled for it so maybe that is the problem..... also is there a way to re-
![bandicam 0089](https://user-images.githubusercontent.com/56183064/87721002-02c73e80-c773-11ea-8478-9e1e0db6befc.jpg)
enable it

**Comment by zenseii** [comment]
> hey i have a question forgive me for not knowing but i looked monster hunter tri up on wiimmfi and it said that online/wiimmfi was disabled for it so maybe that is the problem..... also is there a way to re-
> ![bandicam 0089](https://user-images.githubusercontent.com/56183064/87721002-02c73e80-c773-11ea-8478-9e1e0db6befc.jpg)
> enable it

Wifi connection for it is "disabled" on wiimmfi server because no one has figured out how to reverse engineer the wifi connection stuff for this game that Capcom had going. This is one of special games that had a custom server and not the standard wfc stuff, as far as I've understood things.

**Comment by BrandonMWells** [comment]
Anyone have any packet captures from this game or did someone not nab any around the time of the shutdown notice?

**Comment by TurboBoban** [comment]
Hello everyone, I wanted to comment here because I'm really really interested in accessing Loc Lac again! I'm not really helpful at coding but I'd still like to motivate you all to please keep on working together in a team. If someone has already a discord set up for this project, let me know PLEASE!! I hope that project didn't get completely lost, since I know how time consuming stuff like that can be... I hope to get some answers soon by you all, and may the gates open in the future again
![LocLacGate](https://user-images.githubusercontent.com/76759483/105113646-9af90400-5ac5-11eb-86e6-b2d2dfb86760.jpg)
!

**Comment by danielloera** [comment]
I know a but of coding but was not able to get very far with this project. I'm not very experienced with reverse engineering these types of things.. I hope to see Loc Lac again one day as well.

**Comment by Proryanator** [comment]
I would love to give a shot at reverse-engineering the packets that were captured at some point, and how we could potentially re-create the 'special servers' if I had more free time.

I loved MH3 Tri and, by the time I started playing online, the online servers were shortly killed after that so I didn't get to see Loc Lac a whole lot.

I've played a modded version of MH3 Tri where you can still play the online content (or most of it) but it's just not the same.

Who knows, if I have some time I might try to help push this project along. I've always been interested in game hacking and reverse-engineering, like the project to revive Lego Universe for example, I wanted to help with that.

Best of luck to anyone who tries to push this project further!
