### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by InusualZ** [sepalani/MH3SP#3]
Hi @sepalani

I kind of need your help, I have been trying to reach **85%**, just like you. But it seems there is something wrong with the certificate that I generate. It keep throwing at me the error code [11604](https://forum.wii-homebrew.com/index.php/Thread/51738-Collecting-Error-Codes/) (SSL failed: Wrong CN)

![image](https://user-images.githubusercontent.com/2200611/107894477-a6eeaf00-6f27-11eb-94bd-58d83eaf08a1.png)

This is the original _RMHE08.txt_

![image](https://user-images.githubusercontent.com/2200611/107894243-f1236080-6f26-11eb-833c-abd5b3c7848a.png)

And as you can see mine is almost identical in terms of **_Issuer_**

![image](https://user-images.githubusercontent.com/2200611/107894292-27f97680-6f27-11eb-8cb0-4f4f756a5ea1.png)

As you can see in the first image, I'm using dolphin. I have patched the dump to look for Wiimmfi. I'm I missing something obvious here?

Thanks :)

PD: Do you by any chance have a Symbols Map that you could share?

**Comment by sepalani** [comment]
### CN error
Regarding the CN error, make sure you've generated a Root CA certificate (which seems to be the case according to your screenshot) and [patched the game with it](https://github.com/sepalani/MH3SP/tree/master/cert). Then, you just need to [generate a certificate for your server](https://github.com/sepalani/MHTrIDA/tree/master/server/cert#certificate) matching the [name of Capcom server](https://github.com/sepalani/MHTrIDA/tree/master/server/dns#capcom-domain-names) and use that.

### Quick fix (Dolphin only)
If you have a really recent version of Dolphin (dev) builds, you can enable the debugger view. There is an option in the Network view called "verify certificates". If you untick the checkbox it will bypass the CN verification check. Beware that by doing that you'll make **insecure requests**. You should enable it again if you plan to play online on or download updates from Nintendo servers.

### Symbols
I'm unaware of any symbol maps regarding that games. I use Megazig's WiiTools signature files and symbols from the loaded RSO modules. Both are supported by Dolphin you just need to load them manually.

**Comment by InusualZ** [comment]
Of course, I thought that Dolphin wasn't verifying the certificate by default. Now I'm where you left it.

Thanks that fixed the issue.

**Comment by Radu13** [comment]
@InusualZ It's really nice to see someone else with needed knowledge taking a shot in getting loc-lac reachable again!
My programming knowledge will probably not be enough but I am really good at figuring stuff out with intensive "trial and error" sessions...
Also you want keep going solo trying get it working? Or I may suggesy you create a discord server or something where other skilled people may join and help testing/figuring more?

**Comment by InusualZ** [comment]
I'm going to experiment by self, if I manage to push the project just by a little bit. I'm going to publish my finding. Then we can talk about creating a community.

**Comment by Radu13** [comment]
> I'm going to experiment by self, if I manage to push the project just by a little bit. I'm going to publish my finding. Then we can talk about creating a community.

Sure! I will watch from behind 'till something new happen
