### ISSUE TITLE
[dev] Player position in quest disrupted while moving (and not hosting the quest)

### ISSUE THREAD

**Issue by sepalani** [sepalani/MH3SP#40]
There seem to be no issue while the host is moving. However, when a member of the party is moving it produces an invalid read/write in Dolphin for the hunter hosting a quest. Ignoring it makes players move (temporarily) as the same time imitating the player.

**Comment by soulmizute** [comment]
i think it may be a bug in the host to other player connection script(if there is one)

**Comment by sepalani** [comment]
There is no "connection script", the issue was probably involving the client-side code of the game. I'm unable to reproduce it, ATM, so I suspect it to have been fixed by https://github.com/sepalani/MH3SP/pull/43. I'll reopen it with more details if it occurs again.
